<?php
class Product{
    public $prdID;
    public $ProductID;
    public $countryID;
	public $prdProductClientCode;
	public $ProductName;
	public $prdCreatedOn;
	public $prdGSTGroup;
	public $prdGroup1ID;
	public $prdGroup1ClientID;
	public $prdGroup2ID;
	public $prdGroup2ClientID;
	public $prdGroup2Desc;
	public $prdGroup3ID;
	public $prdGroup3ClientID;
	public $prdGroup3Desc;
	public $prdGroup4ID;
	public $prdGroup4Desc;
	public $prdGroup5ID;
	public $prdGroup5ClientID;
	public $prdGroup5Desc;
	public $prdGroup6ID;
	public $prdGroup6ClientID;
	public $prdGroup6Desc;
	public $prdGroup7ID;
	public $prdGroup7ClientID;
	public $prdGroup7Desc;
	public $prdGroup8ID;
	public $prdGroup8ClientID;
	public $prdGroup8Desc;
	public $prdGroup9ID;
	public $prdGroup9ClientID;
	public $prdGroup9Desc;
    public $prdGroup10ID;
	public $prdGroup10ClientID;
	public $prdGroup10Desc;  
	public $prdGroup11ID;
	public $prdGroup11ClientID;
	public $prdGroup11Desc;
	public $prdGroup12ID;
	public $prdGroup12ClientID;
	public $prdGroup12Desc;
	public $prdGroup13ID;
	public $prdGroup13ClientID;
	public $prdGroup13Desc;
	public $prdGroup14ID;
	public $prdGroup14ClientID;
	public $prdGroup14Desc;
	public $prdGroup15ID;
	public $prdGroup15ClientID;
	public $prdGroup15Desc;	
	public $prdGroup16ID;
	public $prdGroup16ClientID;
	public $prdGroup16Desc;	
	public $prdGroup17ID;
	public $prdGroup17ClientID;
	public $prdGroup17Desc;	
	public $prdGroup18ID;
	public $prdGroup18ClientID;
	public $prdGroup18Desc;	
    public function __construct($prdID, $ProductID, $countryID, $prdProductClientCode, $ProductName, $prdCreatedOn, $prdGSTGroup, $prdGroup1ID, $prdGroup1ClientID, $prdGroup1Desc,$prdGroup2ID, $prdGroup2ClientID, $prdGroup2Desc,$prdGroup3ID, $prdGroup3ClientID, $prdGroup3Desc,$prdGroup4ID, $prdGroup4ClientID, $prdGroup4Desc,$prdGroup5ID, $prdGroup5ClientID, $prdGroup5Desc,$prdGroup6ID, $prdGroup6ClientID, $prdGroup6Desc,$prdGroup7ID, $prdGroup7ClientID, $prdGroup7Desc,$prdGroup8ID, $prdGroup8ClientID, $prdGroup8Desc,$prdGroup9ID, $prdGroup9ClientID, $prdGroup9Desc,$prdGroup10ID, $prdGroup10ClientID, $prdGroup10Desc,$prdGroup11ID, $prdGroup11ClientID, $prdGroup11Desc,$prdGroup12ID, $prdGroup12ClientID, $prdGroup12Desc,$prdGroup13ID, $prdGroup13ClientID, $prdGroup13Desc,$prdGroup14ID, $prdGroup14ClientID, $prdGroup14Desc,$prdGroup15ID, $prdGroup15ClientID, $prdGroup15Desc,$prdGroup16ID, $prdGroup16ClientID, $prdGroup16Desc,$prdGroup17ID, $prdGroup17ClientID, $prdGroup17Desc,$prdGroup18ID, $prdGroup18ClientID, $prdGroup18Desc ) {
        $this->prdID = $prdID;
        $this->ProductID = $ProductID;
        $this->countryID = $countryID;
		$this->prdProductClientCode = $prdProductClientCode;
		$this->ProductName = $ProductName;
		$this->prdCreatedOn = $prdCreatedOn;
		$this->prdGSTGroup = $prdGSTGroup;
		$this->prdGroup1ID = $prdGroup1ID;
		$this->prdGroup1ClientID = $prdGroup1ClientID;
		$this->prdGroup1Desc = $prdGroup1Desc;
		$this->prdGroup2ID = $prdGroup2ID;
		$this->prdGroup2ClientID = $prdGroup2ClientID;
		$this->prdGroup2Desc = $prdGroup2Desc;
		$this->prdGroup3ID = $prdGroup3ID;
		$this->prdGroup3ClientID = $prdGroup3ClientID;
		$this->prdGroup3Desc = $prdGroup3Desc;
		$this->prdGroup4ID = $prdGroup4ID;
		$this->prdGroup4ClientID = $prdGroup4ClientID;
		$this->prdGroup4Desc = $prdGroup4Desc;
		$this->prdGroup5ID = $prdGroup5ID;
		$this->prdGroup5ClientID = $prdGroup5ClientID;
		$this->prdGroup5Desc = $prdGroup5Desc;
		$this->prdGroup6ID = $prdGroup6ID;
		$this->prdGroup6ClientID = $prdGroup6ClientID;
		$this->prdGroup6Desc = $prdGroup6Desc;
		$this->prdGroup7ID = $prdGroup7ID;
		$this->prdGroup7ClientID = $prdGroup7ClientID;
		$this->prdGroup7Desc = $prdGroup7Desc;
		$this->prdGroup8ID = $prdGroup8ID;
		$this->prdGroup8ClientID = $prdGroup8ClientID;
		$this->prdGroup8Desc = $prdGroup8Desc;
		$this->prdGroup9ID = $prdGroup9ID;
		$this->prdGroup9ClientID = $prdGroup9ClientID;
		$this->prdGroup9Desc = $prdGroup9Desc;
		$this->prdGroup10ID = $prdGroup10ID;
		$this->prdGroup10ClientID = $prdGroup10ClientID;
		$this->prdGroup10Desc = $prdGroup10Desc;
		$this->prdGroup11ID = $prdGroup11ID;
		$this->prdGroup11ClientID = $prdGroup11ClientID;
		$this->prdGroup11Desc = $prdGroup11Desc;
		$this->prdGroup12ID = $prdGroup12ID;
		$this->prdGroup12ClientID = $prdGroup12ClientID;
		$this->prdGroup12Desc = $prdGroup12Desc;
		$this->prdGroup13ID = $prdGroup13ID;
		$this->prdGroup13ClientID = $prdGroup13ClientID;
		$this->prdGroup13Desc = $prdGroup13Desc;
		$this->prdGroup14ID = $prdGroup14ID;
		$this->prdGroup14ClientID = $prdGroup14ClientID;
		$this->prdGroup14Desc = $prdGroup14Desc;
		$this->prdGroup15ID = $prdGroup15ID;
		$this->prdGroup15ClientID = $prdGroup15ClientID;
		$this->prdGroup15Desc = $prdGroup15Desc;
		$this->prdGroup16ID = $prdGroup16ID;
		$this->prdGroup16ClientID = $prdGroup16ClientID;
		$this->prdGroup16Desc = $prdGroup16Desc;
		$this->prdGroup17ID = $prdGroup17ID;
		$this->prdGroup17ClientID = $prdGroup17ClientID;
		$this->prdGroup17Desc = $prdGroup17Desc;
		$this->prdGroup18ID = $prdGroup18ID;
		$this->prdGroup18ClientID = $prdGroup18ClientID;
		$this->prdGroup18Desc = $prdGroup1Desc;
		
    }
     
   
}
?>
